version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: solfolio-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-solfolio}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-devpassword}
      POSTGRES_DB: ${POSTGRES_DB:-solfolio_dev}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-solfolio}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - solfolio-network

  redis:
    image: redis:7-alpine
    container_name: solfolio-redis
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - solfolio-network

  envoy:
    image: envoyproxy/envoy:v1.28-latest
    container_name: solfolio-envoy
    ports:
      - "8080:8080"  # gRPC-Web port
      - "9901:9901"  # Admin interface
    volumes:
      - ./docker/envoy/envoy.yaml:/etc/envoy/envoy.yaml
    command: -c /etc/envoy/envoy.yaml
    depends_on:
      - backend
    networks:
      - solfolio-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: solfolio-backend
    environment:
      NODE_ENV: development
      GRPC_PORT: ${GRPC_PORT:-50051}
      DATABASE_URL: postgresql://${POSTGRES_USER:-solfolio}:${POSTGRES_PASSWORD:-devpassword}@postgres:5432/${POSTGRES_DB:-solfolio_dev}
      REDIS_URL: redis://redis:6379
      HELIUS_API_KEY: ${HELIUS_API_KEY}
      JUPITER_API_URL: ${JUPITER_API_URL:-https://price.jup.ag/v4}
    ports:
      - "50051:50051"  # gRPC port
    volumes:
      - ./backend:/app
      - ./proto:/proto
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - solfolio-network
    command: npm run dev

  websocket:
    build:
      context: ./websocket
      dockerfile: Dockerfile.dev
    container_name: solfolio-websocket
    environment:
      NODE_ENV: development
      PORT: ${WEBSOCKET_PORT:-8081}
      REDIS_URL: redis://redis:6379
      GRPC_BACKEND_URL: backend:50051
    ports:
      - "8081:8081"
    volumes:
      - ./websocket:/app
      - /app/node_modules
    depends_on:
      - redis
      - backend
    networks:
      - solfolio-network
    command: npm run dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: solfolio-frontend
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_GRPC_WEB_URL: http://localhost:8080
      NEXT_PUBLIC_WEBSOCKET_URL: ws://localhost:8081
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - envoy
      - websocket
    networks:
      - solfolio-network
    command: npm run dev

  # Development tools
  adminer:
    image: adminer:latest
    container_name: solfolio-adminer
    ports:
      - "8082:8080"
    depends_on:
      - postgres
    networks:
      - solfolio-network
    profiles:
      - tools

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: solfolio-redis-commander
    environment:
      REDIS_HOSTS: local:redis:6379
    ports:
      - "8083:8081"
    depends_on:
      - redis
    networks:
      - solfolio-network
    profiles:
      - tools

networks:
  solfolio-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data: